services:
  ib-gateway:
    image: johntfoster/ib-gateway:latest
    environment:
      TWSUSERID: $TWSUSERID
      TWSPASSWORD: $TWSPASSWORD
      TRADING_MODE: paper
      TZ: 'America/New_York'
    ports:
      - 5900:5900
      - 4002:4002
    restart: always
